@startuml
start

:const char path;

if (!(argc == 2)) then (1) <<#yellow>>
	:fprintf(stderr,"usage...")
	ARG_FAULT; <<#lightpink>>
	stop
else (0)
	:path = *(argv + 1);
	if (!path || *path == '\0') then (1) <<#yellow>>
		:fprintf(stderr, "usage...")
		ARG_FAULT; <<#lightpink>>
		stop
	else (0)
	endif
endif

:return sil_write_snapshot(path); <<#lightgreen>>
floating note left
This call is written in tail position. 
When compiling with optimization on it might
be treated as a sibling/tail call. 

This style is optional, I have other programs
where main is more than just an argument sanitizer
avoiding the need to write a function in tail position.

At this time there is no preference of style. 
- NR. 03/05/2026
end note
stop
@enduml
